const paymentMethods = [
  "ONLINE_PAYMENT",
  "CASH_ON_DELIVERY",
  "KHALTI",
  "ESEWA",
  "NPX",
];

const provinceValues = [
  "Koshi",
  "Madhesh",
  "Bagmati",
  "Gandaki",
  "Lumbini",
  "Karnali",
  "Sudurpashchim",
];

const shippingAddress = {
  type: "object",
  required: ["province", "district", "city", "streetAddress"],
  properties: {
    province: { type: "string", enum: provinceValues, example: "Bagmati" },
    district: { type: "string", minLength: 1, example: "Kathmandu" },
    city: { type: "string", minLength: 2, maxLength: 100, example: "Kathmandu" },
    streetAddress: { type: "string", minLength: 5, maxLength: 255, example: "Thamel 10" },
    landmark: { type: "string", example: "Near chowk" },
  },
};

const responseEnvelope = (schema: Record<string, unknown>) => ({
  type: "object",
  required: ["success", "data"],
  properties: {
    success: { type: "boolean", example: true },
    data: schema,
  },
});

export const swaggerSchemas = {
  Notification: {
    type: "object",
    required: ["id", "title", "message", "body", "type", "target", "isRead", "createdAt", "updatedAt"],
    properties: {
      id: { type: "string", format: "uuid", example: "a02a85ed-b995-4e09-ac14-567f575c119c" },
      title: { type: "string", example: "Order Status Updated" },
      message: { type: "string", example: "Order #DV-20260810-00042 status updated to SHIPPED" },
      body: { type: "string", description: "Compatibility alias of message for push-notification clients.", example: "Order #DV-20260810-00042 status updated to SHIPPED" },
      type: { type: "string", enum: ["ORDER_PLACED", "ORDER_STATUS_UPDATED", "GENERAL"], example: "ORDER_STATUS_UPDATED" },
      target: { type: "string", enum: ["ADMIN", "VENDOR", "USER"], example: "USER" },
      isRead: { type: "boolean", example: false },
      orderId: { type: "integer", nullable: true, example: 42 },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
    },
  },
  NotificationListResponse: {
    type: "object",
    required: ["success", "data", "total"],
    properties: {
      success: { type: "boolean", example: true },
      data: { type: "array", items: { $ref: "#/components/schemas/Notification" } },
      total: { type: "integer", example: 12 },
      unreadTotal: { type: "integer", example: 3 },
      page: { type: "integer", example: 1 },
      limit: { type: "integer", example: 25 },
      totalPages: { type: "integer", example: 1 },
    },
  },
  WishlistItem: {
    type: "object",
    required: ["id", "productId", "variantId", "product", "variant"],
    properties: {
      id: { type: "integer", example: 10 },
      productId: { type: "integer", example: 25 },
      variantId: { type: "integer", nullable: true, example: null },
      product: {
        type: "object",
        required: ["id", "name", "productImages"],
        properties: {
          id: { type: "integer", example: 25 },
          name: { type: "string", example: "Wireless Headphones" },
          description: { type: "string", nullable: true },
          basePrice: { type: "number", example: 2500 },
          finalPrice: { type: "number", example: 2250 },
          discount: { type: "number", nullable: true, example: 10 },
          discountAmount: { type: "number", nullable: true, example: 250 },
          discountPercent: { type: "number", nullable: true, example: 10 },
          discountType: { type: "string", nullable: true, enum: ["PERCENTAGE", "FLAT"] },
          productImages: { type: "array", items: { type: "string" }, example: ["https://cdn.example.com/headphones.jpg"] },
          ageRestriction: { type: "object", nullable: true },
        },
      },
      variant: {
        type: "object",
        nullable: true,
        properties: {
          id: { type: "integer", example: 60 },
          sku: { type: "string", nullable: true },
          basePrice: { type: "number", nullable: true },
          finalPrice: { type: "number", nullable: true },
          variantImages: { type: "array", items: { type: "string" } },
          attributes: { type: "object", nullable: true },
          stock: { type: "integer", nullable: true },
        },
      },
    },
  },
  Wishlist: {
    type: "object",
    required: ["items"],
    properties: {
      id: { type: "integer", nullable: true, example: 1 },
      userId: { type: "integer", nullable: true, example: 42 },
      items: { type: "array", items: { $ref: "#/components/schemas/WishlistItem" } },
    },
  },
  PasswordMessageResponse: {
    type: "object",
    required: ["success", "message"],
    properties: {
      success: { type: "boolean", example: true },
      message: { type: "string", example: "Password reset request sent" },
    },
  },
  DeliveryRider: {
    type: "object",
    required: ["id", "fullName", "phoneNumber", "email", "onDelivery", "userId", "createdAt", "updatedAt"],
    properties: {
      id: { type: "integer", example: 12 },
      fullName: { type: "string", nullable: true, example: "Sita Sharma" },
      phoneNumber: { type: "string", example: "9800000000" },
      email: { type: "string", format: "email", nullable: true, example: "sita@dajuvai.com" },
      onDelivery: { type: "boolean", example: false },
      userId: { type: "integer", nullable: true, example: 24 },
      createdAt: { type: "string", format: "date-time", nullable: true },
      updatedAt: { type: "string", format: "date-time", nullable: true },
    },
  },
  DeliveryOrder: {
    type: "object",
    required: ["id", "orderedById", "totalPrice", "shippingFee", "serviceCharge", "isBuyNow", "paymentStatus", "paymentMethod", "status", "deliveryStatus", "orderItems"],
    properties: {
      id: { type: "integer", example: 101 },
      orderedById: { type: "integer", example: 7 },
      totalPrice: { type: "number", example: 4200 },
      shippingFee: { type: "number", example: 120 },
      serviceCharge: { type: "number", example: 0 },
      isBuyNow: { type: "boolean", example: false },
      paymentStatus: { type: "string", enum: ["PAID", "UNPAID"], example: "PAID" },
      paymentMethod: { type: "string", enum: paymentMethods, example: "CASH_ON_DELIVERY" },
      status: { type: "string", example: "CONFIRMED" },
      deliveryStatus: { type: "string", example: "order_processing" },
      appliedPromoCode: { type: "string", nullable: true },
      phoneNumber: { type: "string", nullable: true },
      instrumentName: { type: "string", nullable: true },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
      orderedBy: { type: "object", nullable: true },
      shippingAddress: { type: "object", nullable: true },
      orderItems: { type: "array", items: { type: "object" } },
    },
  },
  DeliveryAssignment: {
    type: "object",
    required: ["id", "orderId", "riderId", "assignmentStatus", "pickedUpAt", "deliveredAt", "failureReason", "createdAt", "updatedAt"],
    properties: {
      id: { type: "integer", example: 55 },
      orderId: { type: "integer", example: 101 },
      riderId: { type: "integer", example: 12 },
      assignmentStatus: { type: "string", example: "ASSIGNED" },
      pickedUpAt: { type: "string", format: "date-time", nullable: true },
      deliveredAt: { type: "string", format: "date-time", nullable: true },
      failureReason: { type: "string", nullable: true },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
      rider: { $ref: "#/components/schemas/DeliveryRider", nullable: true },
      order: { $ref: "#/components/schemas/DeliveryOrder", nullable: true },
    },
  },
  PaymentInstrument: {
    type: "object",
    required: ["InstrumentCode", "InstitutionName", "InstrumentName"],
    properties: {
      InstrumentCode: { type: "string", example: "001" },
      InstitutionName: { type: "string", example: "Nepal Investment Mega Bank" },
      InstrumentName: { type: "string", example: "Mobile Banking" },
    },
  },
  PlacementItem: {
    type: "object",
    required: ["itemId", "entityId", "displayOrder", "visible", "name", "image"],
    properties: {
      itemId: { type: "integer", example: 42 },
      entityId: { type: "integer", example: 12 },
      entityType: { type: "string", enum: ["category", "subcategory"], example: "category" },
      displayOrder: { type: "integer", example: 0 },
      visible: { type: "boolean", example: true },
      name: { type: "string", example: "Cosmetics & Beauty" },
      image: { type: "string", format: "uri", nullable: true },
      categoryId: { type: "integer", nullable: true, example: 3 },
      categoryName: { type: "string", nullable: true, example: "Fashion" },
      subcategories: { type: "array", items: { $ref: "#/components/schemas/PlacementItem" } },
    },
  },
  CatalogEntity: {
    type: "object",
    required: ["id", "name", "image"],
    properties: {
      id: { type: "integer", example: 12 },
      name: { type: "string", example: "Cosmetics & Beauty" },
      image: { type: "string", format: "uri", nullable: true },
    },
  },
  SearchProductResult: {
    type: "object",
    required: ["id", "name", "effectivePrice", "originalPrice", "inStock"],
    properties: {
      id: { type: "integer", example: 12 },
      name: { type: "string", example: "Glow Face Wash" },
      thumbnailUrl: { type: "string", nullable: true, format: "uri" },
      effectivePrice: { type: "number", example: 450 },
      originalPrice: { type: "number", example: 500 },
      discountPercentage: { type: "number", example: 10 },
      averageRating: { type: "number", example: 4.5 },
      totalReviews: { type: "integer", example: 21 },
      inStock: { type: "boolean", example: true },
      matchedVariant: { type: "object", nullable: true, example: null },
    },
  },
  TaxonomySuggestion: {
    type: "object",
    required: ["id", "name"],
    properties: {
      id: { type: "integer", example: 7 },
      name: { type: "string", example: "Cosmetics & Beauty" },
      image: { type: "string", nullable: true, format: "uri" },
    },
  },
  BrandSuggestion: {
    type: "object",
    required: ["id", "name"],
    properties: {
      id: { type: "integer", example: 3 },
      name: { type: "string", example: "Radiant" },
    },
  },
  SearchCatalogResponse: {
    type: "object",
    required: ["query", "normalizedQuery", "resolvedFilters", "products", "categories", "subcategories", "brands", "totalProducts", "page", "limit", "totalPages"],
    properties: {
      query: { type: "string", example: "cosmetics" },
      normalizedQuery: { type: "string", example: "cosmetics" },
      resolvedFilters: {
        type: "object",
        required: ["categoryIds", "subcategoryIds", "brandNames", "keyword"],
        properties: {
          categoryIds: { type: "array", items: { type: "integer" }, example: [7] },
          subcategoryIds: { type: "array", items: { type: "integer" }, example: [] },
          brandNames: { type: "array", items: { type: "string" }, example: [] },
          keyword: { type: "string", nullable: true, example: null },
        },
      },
      products: { type: "array", items: { $ref: "#/components/schemas/SearchProductResult" } },
      categories: { type: "array", items: { $ref: "#/components/schemas/TaxonomySuggestion" } },
      subcategories: { type: "array", items: { $ref: "#/components/schemas/TaxonomySuggestion" } },
      brands: { type: "array", items: { $ref: "#/components/schemas/BrandSuggestion" } },
      totalProducts: { type: "integer", example: 42 },
      page: { type: "integer", example: 1 },
      limit: { type: "integer", example: 40 },
      totalPages: { type: "integer", example: 2 },
    },
  },
  SearchSuggestionsResponse: {
    type: "object",
    required: ["query", "products", "categories", "brands", "totalProducts"],
    properties: {
      query: { type: "string", example: "headphones" },
      products: { type: "array", items: { $ref: "#/components/schemas/SearchProductResult" } },
      categories: { type: "array", items: { $ref: "#/components/schemas/TaxonomySuggestion" } },
      brands: { type: "array", items: { $ref: "#/components/schemas/BrandSuggestion" } },
      totalProducts: { type: "integer", example: 11 },
    },
  },
  SearchAliasRecord: {
    oneOf: [
      {
        type: "object",
        required: ["id", "canonicalTerm", "normalizedCanonical", "alias", "normalizedAlias", "source", "confidence", "active"],
        properties: {
          id: { type: "integer", example: 4 },
          canonicalTerm: { type: "string", example: "headphones" },
          normalizedCanonical: { type: "string", example: "headphones" },
          alias: { type: "string", example: "head phones" },
          normalizedAlias: { type: "string", example: "head phones" },
          categoryId: { type: "integer", nullable: true, example: null },
          subcategoryId: { type: "integer", nullable: true, example: null },
          locale: { type: "string", nullable: true, example: "en" },
          source: { type: "string", enum: ["CURATED", "ADMIN", "SEARCH_LOG", "PRODUCT_DATA"], example: "ADMIN" },
          confidence: { type: "string", example: "0.950" },
          active: { type: "boolean", example: true },
          approvedAt: { type: "string", format: "date-time", nullable: true },
          createdAt: { type: "string", format: "date-time" },
          updatedAt: { type: "string", format: "date-time" },
        },
      },
      {
        type: "object",
        required: ["id", "normalizedQuery", "targetType", "targetId", "searchCount", "positiveOutcomeCount", "confidence", "active"],
        properties: {
          id: { type: "integer", example: 18 },
          normalizedQuery: { type: "string", example: "head phones" },
          targetType: { type: "string", enum: ["PRODUCT", "CATEGORY", "SUBCATEGORY"], example: "SUBCATEGORY" },
          targetId: { type: "integer", example: 9 },
          searchCount: { type: "integer", example: 12 },
          positiveOutcomeCount: { type: "integer", example: 8 },
          confidence: { type: "string", example: "0.667" },
          active: { type: "boolean", example: false },
          createdAt: { type: "string", format: "date-time" },
          updatedAt: { type: "string", format: "date-time" },
        },
      },
    ],
  },
  CheckoutLineItem: {
    type: "object",
    required: ["productId", "variantId", "name", "quantity", "basePrice", "unitPrice", "lineBaseTotal", "lineTotal", "productDiscount", "dealDiscount", "savingsTotal"],
    properties: {
      productId: { type: "integer", nullable: true, example: 12 },
      variantId: { type: "integer", nullable: true, example: 60 },
      name: { type: "string", example: "RLX Explorer" },
      quantity: { type: "integer", minimum: 0, example: 2 },
      basePrice: { type: "number", example: 5000 },
      unitPrice: { type: "number", example: 4200 },
      lineBaseTotal: { type: "number", example: 10000 },
      lineTotal: { type: "number", example: 8400 },
      productDiscount: {
        type: "object",
        required: ["label", "type", "amount"],
        properties: {
          label: { type: "string", nullable: true, example: "10% discount" },
          type: { type: "string", example: "PERCENTAGE" },
          amount: { type: "number", example: 1000 },
        },
      },
      dealDiscount: {
        type: "object",
        required: ["label", "percent", "amount"],
        properties: {
          label: { type: "string", nullable: true, example: "Summer Deal" },
          percent: { type: "number", nullable: true, example: 10 },
          amount: { type: "number", example: 0 },
        },
      },
      savingsTotal: { type: "number", example: 1000 },
    },
  },
  CheckoutPriceBreakdown: {
    type: "object",
    required: ["actualPrice", "merchandiseSubtotal", "productDiscountTotal", "dealDiscountTotal", "promoDiscountTotal", "appliedPromoCode", "lineItems"],
    properties: {
      actualPrice: { type: "number", example: 10000 },
      merchandiseSubtotal: { type: "number", example: 8400 },
      productDiscountTotal: { type: "number", example: 1000 },
      dealDiscountTotal: { type: "number", example: 0 },
      promoDiscountTotal: { type: "number", example: 500 },
      appliedPromoCode: { type: "string", nullable: true, example: "SUMMER2025" },
      lineItems: { type: "array", items: { $ref: "#/components/schemas/CheckoutLineItem" } },
    },
  },
  VendorShippingBreakdown: {
    type: "object",
    required: ["vendorId", "vendorName", "vendorDistrict", "customerDistrict", "shippingZone", "shippingFee", "merchandiseSubtotal"],
    properties: {
      vendorId: { type: "integer", example: 2 },
      vendorName: { type: "string", example: "RLX Watches Nepal" },
      vendorDistrict: { type: "object", nullable: true },
      customerDistrict: { type: "object", nullable: true },
      shippingZone: { type: "string", nullable: true, example: "SAME_DISTRICT" },
      shippingFee: { type: "number", example: 120 },
      merchandiseSubtotal: { type: "number", example: 8400 },
    },
  },
  CheckoutEstimate: {
    type: "object",
    required: ["merchandiseSubtotal", "priceBreakdown", "vendorShippingBreakdown", "shippingTotal", "discountTotal", "appliedPromoCode", "taxTotal", "grandTotal"],
    properties: {
      merchandiseSubtotal: { type: "number", example: 8400 },
      priceBreakdown: { $ref: "#/components/schemas/CheckoutPriceBreakdown" },
      vendorShippingBreakdown: { type: "array", items: { $ref: "#/components/schemas/VendorShippingBreakdown" } },
      shippingTotal: { type: "number", example: 120 },
      discountTotal: { type: "number", example: 500 },
      appliedPromoCode: { type: "string", nullable: true, example: "SUMMER2025" },
      taxTotal: { type: "number", example: 0 },
      grandTotal: { type: "number", example: 8020 },
    },
  },
  CheckoutEstimateResponse: responseEnvelope({ $ref: "#/components/schemas/CheckoutEstimate" }),
  MobileCheckoutEstimateRequest: {
    type: "object",
    required: ["shippingAddress"],
    properties: {
      shippingAddress,
      promoCode: { type: "string", example: "SUMMER" },
      isBuyNow: { type: "boolean", example: false },
      productId: { type: "integer", minimum: 1, example: 12 },
      variantId: { type: "integer", minimum: 1, example: 60 },
      quantity: { type: "integer", minimum: 1, example: 1 },
    },
  },
  CreateOrderRequest: {
    type: "object",
    required: ["shippingAddress", "paymentMethod", "phoneNumber"],
    properties: {
      shippingAddress,
      paymentMethod: { type: "string", enum: paymentMethods, example: "CASH_ON_DELIVERY" },
      phoneNumber: { type: "string", pattern: "^\\d{10}$", minLength: 10, maxLength: 10, example: "9800000000" },
      serviceCharge: { type: "number", minimum: 0, example: 0, description: "Optional client-supplied service charge; server totals remain authoritative." },
      instrumentName: { type: "string", maxLength: 100, example: "Mobile Banking" },
      fullName: { type: "string", example: "Ramesh Shah" },
      promoCode: { type: "string", example: "SUMMER" },
      idempotencyKey: { type: "string", minLength: 1, maxLength: 100, example: "checkout-7d2a4c" },
      ageRestrictedAcknowledged: { type: "boolean", example: false },
      isBuyNow: { type: "boolean", example: false, description: "When true, productId is required and the authenticated cart is bypassed." },
      productId: { type: "integer", minimum: 1, example: 12, description: "Required when isBuyNow is true." },
      variantId: { type: "integer", minimum: 1, example: 60 },
      quantity: { type: "integer", minimum: 1, example: 1 },
    },
  },
  CreateOrderDraftResponse: {
    type: "object",
    required: ["success", "draft", "data"],
    properties: {
      success: { type: "boolean", example: true },
      draft: { type: "boolean", example: true },
      data: {
        type: "object",
        required: ["id", "draftId", "orderNumber", "totalPrice", "paymentMethod"],
        properties: {
          id: { type: "integer", example: 42 },
          draftId: { type: "integer", example: 42 },
          orderNumber: { type: "string", example: "DV-20260805-00042" },
          totalPrice: { type: "number", example: 8020 },
          paymentMethod: { type: "string", enum: paymentMethods, example: "ESEWA" },
        },
      },
      esewaRedirectUrl: { type: "string", format: "uri", nullable: true },
    },
  },
  CreateOrderResponse: {
    type: "object",
    required: ["success", "data", "orderSummary", "orderId", "orderNumber", "paymentMethod", "paymentStatus", "subtotal", "shippingTotal", "discountTotal", "taxTotal", "grandTotal", "itemCount", "priceBreakdown"],
    properties: {
      success: { type: "boolean", example: true },
      data: { $ref: "#/components/schemas/Order" },
      orderSummary: {
        type: "object",
        required: ["orderId", "orderNumber", "paymentMethod", "paymentStatus", "subtotal", "shippingTotal", "discountTotal", "taxTotal", "grandTotal", "itemCount", "priceBreakdown"],
        properties: {
          orderId: { type: "integer", example: 42 },
          orderNumber: { type: "string", example: "DV-20260805-00042" },
          paymentMethod: { type: "string", enum: paymentMethods, example: "CASH_ON_DELIVERY" },
          paymentStatus: { type: "string", enum: ["PAID", "UNPAID"], example: "UNPAID" },
          subtotal: { type: "number", example: 4200 },
          shippingTotal: { type: "number", example: 120 },
          discountTotal: { type: "number", example: 300 },
          taxTotal: { type: "number", example: 0 },
          grandTotal: { type: "number", example: 4020 },
          itemCount: { type: "integer", example: 2 },
          priceBreakdown: { type: "object", nullable: true },
        },
      },
      orderId: { type: "integer", example: 42 },
      orderNumber: { type: "string", example: "DV-20260805-00042" },
      paymentMethod: { type: "string", enum: paymentMethods, example: "CASH_ON_DELIVERY" },
      paymentStatus: { type: "string", enum: ["PAID", "UNPAID"], example: "UNPAID" },
      subtotal: { type: "number", example: 4200 },
      shippingTotal: { type: "number", example: 120 },
      discountTotal: { type: "number", example: 300 },
      taxTotal: { type: "number", example: 0 },
      grandTotal: { type: "number", example: 4020 },
      itemCount: { type: "integer", example: 2 },
      priceBreakdown: { type: "object", nullable: true },
      esewaRedirectUrl: { type: "string", format: "uri", nullable: true, example: "https://rc-epay.esewa.com.np/api/epay/main/v2/form" },
    },
  },
  MobileCheckoutResponse: {
    type: "object",
    required: ["user", "cart", "checkoutReady", "missingCheckoutFields", "checkoutDefaults", "availablePaymentMethods", "checkoutEstimate", "checkoutEstimateError", "priceBreakdown", "vendorShippingBreakdown", "totals"],
    properties: {
      user: { type: "object", required: ["id", "fullName", "username", "email", "phoneNumber", "role"], properties: { id: { type: "integer", example: 5 }, fullName: { type: "string", example: "Ramesh Shah" }, username: { type: "string", example: "ramesh" }, email: { type: "string", format: "email", example: "ramesh@example.com" }, phoneNumber: { type: "string", example: "9800000000" }, role: { type: "string", example: "user" }, address: { type: "object", nullable: true } } },
      cart: {
        type: "object",
        required: ["id", "total", "items"],
        properties: {
          id: { type: "integer", nullable: true, example: 3 },
          total: { type: "number", example: 4200 },
          items: {
            type: "array",
            items: {
              type: "object",
              required: ["id", "productId", "name", "price", "quantity", "image", "variantId", "priceBreakdown", "product", "variant", "vendor"],
              properties: {
                id: { type: "integer", example: 7 },
                productId: { type: "integer", nullable: true, example: 12 },
                name: { type: "string", example: "RLX Explorer - Gray" },
                price: { type: "number", example: 6999 },
                quantity: { type: "integer", example: 2 },
                image: { type: "string", format: "uri", nullable: true },
                variantId: { type: "integer", nullable: true, example: 60 },
                priceBreakdown: { type: "object", nullable: true },
                product: {
                  type: "object",
                  nullable: true,
                  properties: {
                    id: { type: "integer", example: 12 },
                    name: { type: "string", example: "RLX Explorer" },
                    basePrice: { type: "number", nullable: true },
                    finalPrice: { type: "number", nullable: true },
                    discountAmount: { type: "number" },
                    discountPercent: { type: "number" },
                    discountType: { type: "string", nullable: true },
                    productImages: { type: "array", items: { type: "string" } },
                    deal: { type: "object", nullable: true },
                  },
                },
                variant: {
                  type: "object",
                  nullable: true,
                  properties: {
                    id: { type: "integer", example: 60 },
                    sku: { type: "string", nullable: true },
                    basePrice: { type: "number", nullable: true },
                    finalPrice: { type: "number", nullable: true },
                    discountAmount: { type: "number", nullable: true },
                    discountPercent: { type: "number", nullable: true },
                    discountType: { type: "string", nullable: true },
                    attributes: { type: "object", nullable: true },
                    variantImages: { type: "array", items: { type: "string" } },
                    stock: { type: "integer", nullable: true },
                  },
                },
                vendor: {
                  type: "object",
                  nullable: true,
                  properties: {
                    id: { type: "integer", example: 2 },
                    businessName: { type: "string", example: "RLX Watches Nepal" },
                    email: { type: "string", format: "email" },
                    phoneNumber: { type: "string" },
                    districtId: { type: "integer", nullable: true },
                    district: { type: "object", nullable: true },
                  },
                },
              },
            },
          },
        },
      },
      checkoutReady: { type: "boolean", example: true },
      missingCheckoutFields: { type: "array", items: { type: "string" }, example: [] },
      checkoutDefaults: { type: "object", properties: { fullName: { type: "string" }, phoneNumber: { type: "string" }, shippingAddress: { $ref: "#/components/schemas/MobileShippingAddress" }, paymentMethod: { type: "string", enum: paymentMethods } } },
      availablePaymentMethods: { type: "array", items: { type: "string", enum: paymentMethods }, example: ["CASH_ON_DELIVERY", "ESEWA", "NPX"] },
      checkoutEstimate: { $ref: "#/components/schemas/CheckoutEstimate", nullable: true },
      checkoutEstimateError: { type: "string", nullable: true, example: null },
      priceBreakdown: { type: "object", nullable: true },
      vendorShippingBreakdown: { type: "array", items: { type: "object" } },
      totals: { type: "object", nullable: true },
    },
  },
  MobileCheckoutDetailsResponse: responseEnvelope({ $ref: "#/components/schemas/MobileCheckoutResponse" }),
  MobileShippingAddress: shippingAddress,
};
