const paymentMethods = [
  "ONLINE_PAYMENT",
  "CASH_ON_DELIVERY",
  "KHALTI",
  "ESEWA",
  "NPX",
];

const provinceValues = [
  "Koshi",
  "Madhesh",
  "Bagmati",
  "Gandaki",
  "Lumbini",
  "Karnali",
  "Sudurpashchim",
];

const shippingAddress = {
  type: "object",
  required: ["province", "district", "city", "streetAddress"],
  properties: {
    province: { type: "string", enum: provinceValues, example: "Bagmati" },
    district: { type: "string", example: "Kathmandu" },
    city: { type: "string", example: "Kathmandu" },
    streetAddress: { type: "string", example: "Thamel 10" },
    landmark: { type: "string", example: "Near chowk" },
  },
};

const responseEnvelope = (schema: Record<string, unknown>) => ({
  type: "object",
  required: ["success", "data"],
  properties: {
    success: { type: "boolean", example: true },
    data: schema,
  },
});

export const swaggerSchemas = {
  DeliveryRider: {
    type: "object",
    required: ["id", "fullName", "phoneNumber", "email", "onDelivery", "userId", "createdAt", "updatedAt"],
    properties: {
      id: { type: "integer", example: 12 },
      fullName: { type: "string", nullable: true, example: "Sita Sharma" },
      phoneNumber: { type: "string", example: "9800000000" },
      email: { type: "string", format: "email", nullable: true, example: "sita@dajuvai.com" },
      onDelivery: { type: "boolean", example: false },
      userId: { type: "integer", nullable: true, example: 24 },
      createdAt: { type: "string", format: "date-time", nullable: true },
      updatedAt: { type: "string", format: "date-time", nullable: true },
    },
  },
  DeliveryOrder: {
    type: "object",
    required: ["id", "orderedById", "totalPrice", "shippingFee", "serviceCharge", "isBuyNow", "paymentStatus", "paymentMethod", "status", "deliveryStatus", "orderItems"],
    properties: {
      id: { type: "integer", example: 101 },
      orderedById: { type: "integer", example: 7 },
      totalPrice: { type: "number", example: 4200 },
      shippingFee: { type: "number", example: 120 },
      serviceCharge: { type: "number", example: 0 },
      isBuyNow: { type: "boolean", example: false },
      paymentStatus: { type: "string", enum: ["PAID", "UNPAID"], example: "PAID" },
      paymentMethod: { type: "string", enum: paymentMethods, example: "CASH_ON_DELIVERY" },
      status: { type: "string", example: "CONFIRMED" },
      deliveryStatus: { type: "string", example: "order_processing" },
      appliedPromoCode: { type: "string", nullable: true },
      phoneNumber: { type: "string", nullable: true },
      instrumentName: { type: "string", nullable: true },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
      orderedBy: { type: "object", nullable: true },
      shippingAddress: { type: "object", nullable: true },
      orderItems: { type: "array", items: { type: "object" } },
    },
  },
  DeliveryAssignment: {
    type: "object",
    required: ["id", "orderId", "riderId", "assignmentStatus", "pickedUpAt", "deliveredAt", "failureReason", "createdAt", "updatedAt"],
    properties: {
      id: { type: "integer", example: 55 },
      orderId: { type: "integer", example: 101 },
      riderId: { type: "integer", example: 12 },
      assignmentStatus: { type: "string", example: "ASSIGNED" },
      pickedUpAt: { type: "string", format: "date-time", nullable: true },
      deliveredAt: { type: "string", format: "date-time", nullable: true },
      failureReason: { type: "string", nullable: true },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
      rider: { $ref: "#/components/schemas/DeliveryRider", nullable: true },
      order: { $ref: "#/components/schemas/DeliveryOrder", nullable: true },
    },
  },
  PaymentInstrument: {
    type: "object",
    required: ["InstrumentCode", "InstitutionName", "InstrumentName"],
    properties: {
      InstrumentCode: { type: "string", example: "001" },
      InstitutionName: { type: "string", example: "Nepal Investment Mega Bank" },
      InstrumentName: { type: "string", example: "Mobile Banking" },
    },
  },
  PlacementItem: {
    type: "object",
    required: ["itemId", "entityId", "displayOrder", "visible", "name", "image"],
    properties: {
      itemId: { type: "integer", example: 42 },
      entityId: { type: "integer", example: 12 },
      entityType: { type: "string", enum: ["category", "subcategory"], example: "category" },
      displayOrder: { type: "integer", example: 0 },
      visible: { type: "boolean", example: true },
      name: { type: "string", example: "Cosmetics & Beauty" },
      image: { type: "string", format: "uri", nullable: true },
      categoryId: { type: "integer", nullable: true, example: 3 },
      categoryName: { type: "string", nullable: true, example: "Fashion" },
      subcategories: { type: "array", items: { $ref: "#/components/schemas/PlacementItem" } },
    },
  },
  CatalogEntity: {
    type: "object",
    required: ["id", "name", "image"],
    properties: {
      id: { type: "integer", example: 12 },
      name: { type: "string", example: "Cosmetics & Beauty" },
      image: { type: "string", format: "uri", nullable: true },
    },
  },
  SearchProductResult: {
    type: "object",
    required: ["id", "name", "effectivePrice", "originalPrice", "inStock"],
    properties: {
      id: { type: "integer", example: 12 },
      name: { type: "string", example: "Glow Face Wash" },
      thumbnailUrl: { type: "string", nullable: true, format: "uri" },
      effectivePrice: { type: "number", example: 450 },
      originalPrice: { type: "number", example: 500 },
      discountPercentage: { type: "number", example: 10 },
      averageRating: { type: "number", example: 4.5 },
      totalReviews: { type: "integer", example: 21 },
      inStock: { type: "boolean", example: true },
      matchedVariant: { type: "object", nullable: true, example: null },
    },
  },
  TaxonomySuggestion: {
    type: "object",
    required: ["id", "name"],
    properties: {
      id: { type: "integer", example: 7 },
      name: { type: "string", example: "Cosmetics & Beauty" },
      image: { type: "string", nullable: true, format: "uri" },
    },
  },
  BrandSuggestion: {
    type: "object",
    required: ["id", "name"],
    properties: {
      id: { type: "integer", example: 3 },
      name: { type: "string", example: "Radiant" },
    },
  },
  SearchCatalogResponse: {
    type: "object",
    required: ["query", "normalizedQuery", "resolvedFilters", "products", "categories", "subcategories", "brands", "totalProducts", "page", "limit", "totalPages"],
    properties: {
      query: { type: "string", example: "cosmetics" },
      normalizedQuery: { type: "string", example: "cosmetics" },
      resolvedFilters: {
        type: "object",
        required: ["categoryIds", "subcategoryIds", "brandNames", "keyword"],
        properties: {
          categoryIds: { type: "array", items: { type: "integer" }, example: [7] },
          subcategoryIds: { type: "array", items: { type: "integer" }, example: [] },
          brandNames: { type: "array", items: { type: "string" }, example: [] },
          keyword: { type: "string", nullable: true, example: null },
        },
      },
      products: { type: "array", items: { $ref: "#/components/schemas/SearchProductResult" } },
      categories: { type: "array", items: { $ref: "#/components/schemas/TaxonomySuggestion" } },
      subcategories: { type: "array", items: { $ref: "#/components/schemas/TaxonomySuggestion" } },
      brands: { type: "array", items: { $ref: "#/components/schemas/BrandSuggestion" } },
      totalProducts: { type: "integer", example: 42 },
      page: { type: "integer", example: 1 },
      limit: { type: "integer", example: 40 },
      totalPages: { type: "integer", example: 2 },
    },
  },
  SearchSuggestionsResponse: {
    type: "object",
    required: ["query", "products", "categories", "brands", "totalProducts"],
    properties: {
      query: { type: "string", example: "headphones" },
      products: { type: "array", items: { $ref: "#/components/schemas/SearchProductResult" } },
      categories: { type: "array", items: { $ref: "#/components/schemas/TaxonomySuggestion" } },
      brands: { type: "array", items: { $ref: "#/components/schemas/BrandSuggestion" } },
      totalProducts: { type: "integer", example: 11 },
    },
  },
  SearchAliasRecord: {
    oneOf: [
      {
        type: "object",
        required: ["id", "canonicalTerm", "normalizedCanonical", "alias", "normalizedAlias", "source", "confidence", "active"],
        properties: {
          id: { type: "integer", example: 4 },
          canonicalTerm: { type: "string", example: "headphones" },
          normalizedCanonical: { type: "string", example: "headphones" },
          alias: { type: "string", example: "head phones" },
          normalizedAlias: { type: "string", example: "head phones" },
          categoryId: { type: "integer", nullable: true, example: null },
          subcategoryId: { type: "integer", nullable: true, example: null },
          locale: { type: "string", nullable: true, example: "en" },
          source: { type: "string", enum: ["CURATED", "ADMIN", "SEARCH_LOG", "PRODUCT_DATA"], example: "ADMIN" },
          confidence: { type: "string", example: "0.950" },
          active: { type: "boolean", example: true },
          approvedAt: { type: "string", format: "date-time", nullable: true },
          createdAt: { type: "string", format: "date-time" },
          updatedAt: { type: "string", format: "date-time" },
        },
      },
      {
        type: "object",
        required: ["id", "normalizedQuery", "targetType", "targetId", "searchCount", "positiveOutcomeCount", "confidence", "active"],
        properties: {
          id: { type: "integer", example: 18 },
          normalizedQuery: { type: "string", example: "head phones" },
          targetType: { type: "string", enum: ["PRODUCT", "CATEGORY", "SUBCATEGORY"], example: "SUBCATEGORY" },
          targetId: { type: "integer", example: 9 },
          searchCount: { type: "integer", example: 12 },
          positiveOutcomeCount: { type: "integer", example: 8 },
          confidence: { type: "string", example: "0.667" },
          active: { type: "boolean", example: false },
          createdAt: { type: "string", format: "date-time" },
          updatedAt: { type: "string", format: "date-time" },
        },
      },
    ],
  },
  CheckoutEstimate: {
    type: "object",
    required: ["merchandiseSubtotal", "shippingTotal", "discountTotal", "taxTotal", "grandTotal"],
    properties: {
      merchandiseSubtotal: { type: "number", example: 4200 },
      priceBreakdown: { type: "object", nullable: true },
      vendorShippingBreakdown: { type: "array", items: { type: "object" } },
      shippingTotal: { type: "number", example: 120 },
      discountTotal: { type: "number", example: 300 },
      appliedPromoCode: { type: "string", nullable: true, example: null },
      taxTotal: { type: "number", example: 0 },
      grandTotal: { type: "number", example: 4020 },
    },
  },
  CheckoutEstimateResponse: responseEnvelope({ $ref: "#/components/schemas/CheckoutEstimate" }),
  MobileCheckoutEstimateRequest: {
    type: "object",
    required: ["shippingAddress"],
    properties: {
      shippingAddress,
      promoCode: { type: "string", example: "SUMMER" },
      isBuyNow: { type: "boolean", example: false },
      productId: { type: "integer", minimum: 1, example: 12 },
      variantId: { type: "integer", minimum: 1, example: 60 },
      quantity: { type: "integer", minimum: 1, example: 1 },
    },
  },
  CreateOrderRequest: {
    type: "object",
    required: ["shippingAddress", "paymentMethod", "phoneNumber"],
    properties: {
      shippingAddress,
      paymentMethod: { type: "string", enum: paymentMethods, example: "CASH_ON_DELIVERY" },
      phoneNumber: { type: "string", minLength: 10, maxLength: 10, example: "9800000000" },
      fullName: { type: "string", example: "Ramesh Shah" },
      promoCode: { type: "string", example: "SUMMER" },
      ageRestrictedAcknowledged: { type: "boolean", example: false },
      isBuyNow: { type: "boolean", example: false },
      productId: { type: "integer", minimum: 1, example: 12 },
      variantId: { type: "number", minimum: 1, example: 60 },
      quantity: { type: "integer", minimum: 1, example: 1 },
    },
  },
  CreateOrderResponse: {
    type: "object",
    required: ["success", "data", "orderSummary", "orderId", "orderNumber", "paymentMethod", "paymentStatus", "subtotal", "shippingTotal", "discountTotal", "taxTotal", "grandTotal", "itemCount", "priceBreakdown"],
    properties: {
      success: { type: "boolean", example: true },
      data: { $ref: "#/components/schemas/Order" },
      orderSummary: {
        type: "object",
        required: ["orderId", "orderNumber", "paymentMethod", "paymentStatus", "subtotal", "shippingTotal", "discountTotal", "taxTotal", "grandTotal", "itemCount", "priceBreakdown"],
        properties: {
          orderId: { type: "integer", example: 42 },
          orderNumber: { type: "string", example: "DV-20260805-00042" },
          paymentMethod: { type: "string", enum: paymentMethods, example: "CASH_ON_DELIVERY" },
          paymentStatus: { type: "string", enum: ["PAID", "UNPAID"], example: "UNPAID" },
          subtotal: { type: "number", example: 4200 },
          shippingTotal: { type: "number", example: 120 },
          discountTotal: { type: "number", example: 300 },
          taxTotal: { type: "number", example: 0 },
          grandTotal: { type: "number", example: 4020 },
          itemCount: { type: "integer", example: 2 },
          priceBreakdown: { type: "object", nullable: true },
        },
      },
      orderId: { type: "integer", example: 42 },
      orderNumber: { type: "string", example: "DV-20260805-00042" },
      paymentMethod: { type: "string", enum: paymentMethods, example: "CASH_ON_DELIVERY" },
      paymentStatus: { type: "string", enum: ["PAID", "UNPAID"], example: "UNPAID" },
      subtotal: { type: "number", example: 4200 },
      shippingTotal: { type: "number", example: 120 },
      discountTotal: { type: "number", example: 300 },
      taxTotal: { type: "number", example: 0 },
      grandTotal: { type: "number", example: 4020 },
      itemCount: { type: "integer", example: 2 },
      priceBreakdown: { type: "object", nullable: true },
      esewaRedirectUrl: { type: "string", format: "uri", nullable: true, example: "https://rc-epay.esewa.com.np/api/epay/main/v2/form" },
    },
  },
  MobileCheckoutResponse: {
    type: "object",
    required: ["user", "cart", "checkoutReady", "missingCheckoutFields", "checkoutDefaults", "availablePaymentMethods", "checkoutEstimate", "checkoutEstimateError", "priceBreakdown", "vendorShippingBreakdown", "totals"],
    properties: {
      user: { type: "object", required: ["id", "fullName", "username", "email", "phoneNumber", "role"], properties: { id: { type: "integer", example: 5 }, fullName: { type: "string", example: "Ramesh Shah" }, username: { type: "string", example: "ramesh" }, email: { type: "string", format: "email", example: "ramesh@example.com" }, phoneNumber: { type: "string", example: "9800000000" }, role: { type: "string", example: "user" }, address: { type: "object", nullable: true } } },
      cart: {
        type: "object",
        required: ["id", "total", "items"],
        properties: {
          id: { type: "integer", nullable: true, example: 3 },
          total: { type: "number", example: 4200 },
          items: {
            type: "array",
            items: {
              type: "object",
              required: ["id", "productId", "name", "price", "quantity", "image", "variantId", "priceBreakdown", "product", "variant", "vendor"],
              properties: {
                id: { type: "integer", example: 7 },
                productId: { type: "integer", nullable: true, example: 12 },
                name: { type: "string", example: "RLX Explorer - Gray" },
                price: { type: "number", example: 6999 },
                quantity: { type: "integer", example: 2 },
                image: { type: "string", format: "uri", nullable: true },
                variantId: { type: "integer", nullable: true, example: 60 },
                priceBreakdown: { type: "object", nullable: true },
                product: {
                  type: "object",
                  nullable: true,
                  properties: {
                    id: { type: "integer", example: 12 },
                    name: { type: "string", example: "RLX Explorer" },
                    basePrice: { type: "number", nullable: true },
                    finalPrice: { type: "number", nullable: true },
                    discountAmount: { type: "number" },
                    discountPercent: { type: "number" },
                    discountType: { type: "string", nullable: true },
                    productImages: { type: "array", items: { type: "string" } },
                    deal: { type: "object", nullable: true },
                  },
                },
                variant: {
                  type: "object",
                  nullable: true,
                  properties: {
                    id: { type: "integer", example: 60 },
                    sku: { type: "string", nullable: true },
                    basePrice: { type: "number", nullable: true },
                    finalPrice: { type: "number", nullable: true },
                    discountAmount: { type: "number", nullable: true },
                    discountPercent: { type: "number", nullable: true },
                    discountType: { type: "string", nullable: true },
                    attributes: { type: "object", nullable: true },
                    variantImages: { type: "array", items: { type: "string" } },
                    stock: { type: "integer", nullable: true },
                  },
                },
                vendor: {
                  type: "object",
                  nullable: true,
                  properties: {
                    id: { type: "integer", example: 2 },
                    businessName: { type: "string", example: "RLX Watches Nepal" },
                    email: { type: "string", format: "email" },
                    phoneNumber: { type: "string" },
                    districtId: { type: "integer", nullable: true },
                    district: { type: "object", nullable: true },
                  },
                },
              },
            },
          },
        },
      },
      checkoutReady: { type: "boolean", example: true },
      missingCheckoutFields: { type: "array", items: { type: "string" }, example: [] },
      checkoutDefaults: { type: "object", properties: { fullName: { type: "string" }, phoneNumber: { type: "string" }, shippingAddress: { $ref: "#/components/schemas/MobileShippingAddress" }, paymentMethod: { type: "string", enum: paymentMethods } } },
      availablePaymentMethods: { type: "array", items: { type: "string", enum: paymentMethods }, example: ["CASH_ON_DELIVERY", "ESEWA", "NPX"] },
      checkoutEstimate: { $ref: "#/components/schemas/CheckoutEstimate", nullable: true },
      checkoutEstimateError: { type: "string", nullable: true, example: null },
      priceBreakdown: { type: "object", nullable: true },
      vendorShippingBreakdown: { type: "array", items: { type: "object" } },
      totals: { type: "object", nullable: true },
    },
  },
  MobileCheckoutDetailsResponse: responseEnvelope({ $ref: "#/components/schemas/MobileCheckoutResponse" }),
  MobileShippingAddress: shippingAddress,
};
